name: Scout

on: [push]

jobs: 
  docker_scout:
    name: Docker Scout
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '25.0.0'
    
    - name: Build Docker Image
      run: docker build -t app:latest .
    
    - name: Docker Scout
      run: |
        curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker scout quickview
        docker scout cves
