name: Ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    steps:
      - name: Run Ruff Checks
        uses: chartboost/ruff-action@v1

