name: Ruff

on: [push]

jobs:
  ruff_check:
    name: Run Ruff Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff Checks
        uses: chartboost/ruff-action@v1

